export const SUPPLIERS = [
	{
		slug: "azamara",
		name: "Azamara",
		logoSrc: "/logos/azamara_logo.svg",
		website: "https://www.azamara.com",
		isLightLogo: false,
		tagline: "Destination immersion with longer stays.",
		description:
			"Azamara specializes in destination-focused voyages with more overnights and late departures, giving travelers extra time to discover each port.",
		highlights: ["Longer port stays", "Overnight calls", "Cultural destination focus"],
	},
	{
		slug: "celebrity-cruises",
		name: "Celebrity Cruises",
		logoSrc: "/logos/celebrity-cruises_logo.svg",
		website: "https://www.celebritycruises.com",
		isLightLogo: true,
		tagline: "Modern luxury at sea.",
		description: "Celebrity combines contemporary design, premium service, and globally inspired dining on modern ships crafted for elevated travel.",
		highlights: ["Modern ship design", "Premium service", "Refined culinary program"],
	},
	{
		slug: "cunard",
		name: "Cunard",
		logoSrc: "/logos/cunard-line_logo.svg",
		website: "https://www.cunard.com",
		isLightLogo: false,
		tagline: "Iconic ocean travel traditions.",
		description: "Cunard is known for transatlantic crossings, classic elegance, and a timeless onboard atmosphere inspired by grand ocean liner heritage.",
		highlights: ["Transatlantic expertise", "Classic elegance", "Signature white-glove style"],
	},
	{
		slug: "explora-journeys",
		name: "Explora Journeys",
		logoSrc: "/logos/explora-journeys_logo.svg",
		website: "https://explorajourneys.com",
		isLightLogo: false,
		tagline: "Ocean travel reimagined.",
		description: "Explora Journeys offers a contemporary luxury cruise concept with spacious suites, flexible experiences, and thoughtfully paced itineraries.",
		highlights: ["All-suite concept", "Contemporary luxury", "Slow and immersive routes"],
	},
	{
		slug: "holland-america-line",
		name: "Holland America Line",
		logoSrc: "/logos/holland-america-line_logo.svg",
		website: "https://www.hollandamerica.com",
		isLightLogo: false,
		tagline: "Classic cruising with global reach.",
		description:
			"Holland America Line delivers classic premium cruising with carefully crafted itineraries, strong culinary programming, and destination depth.",
		highlights: ["Global itineraries", "Premium classic style", "Destination-rich programming"],
	},
	{
		slug: "lindblad-expeditions",
		name: "Lindblad Expeditions",
		logoSrc: "/logos/lindblad_logo.svg",
		website: "https://www.expeditions.com",
		isLightLogo: true,
		tagline: "Expedition cruising for curious explorers.",
		description: "Lindblad Expeditions focuses on adventure and natural discovery, featuring expert-led itineraries in remote and wildlife-rich destinations.",
		highlights: ["Remote destinations", "Expert naturalists", "Adventure-led voyages"],
	},
	{
		slug: "msc-cruises",
		name: "MSC Cruises",
		logoSrc: "/logos/msc_logo.svg",
		website: "https://www.msccruises.com",
		isLightLogo: false,
		tagline: "European style cruising worldwide.",
		description: "MSC Cruises combines European hospitality, family-friendly experiences, and contemporary ships sailing in major regions around the world.",
		highlights: ["European heritage", "Family-friendly options", "Modern fleet"],
	},
	{
		slug: "norwegian-cruise-line",
		name: "Norwegian Cruise Line",
		logoSrc: "/logos/norwegian-cruise-line_logo.svg",
		website: "https://www.ncl.com",
		isLightLogo: true,
		tagline: "Award-winning ships and experiences.",
		description: "Norwegian Cruise Line offers dynamic ship experiences, diverse itineraries, and a casual premium approach centered on guest freedom.",
		highlights: ["Dynamic ship experiences", "Casual premium ambiance", "Wide itinerary selection"],
	},
	{
		slug: "oceania-cruises",
		name: "Oceania Cruises",
		logoSrc: "/logos/oceania-cruises_logo.svg",
		website: "https://www.oceaniacruises.com",
		isLightLogo: true,
		tagline: "The finest cuisine at sea.",
		description: "Oceania is a premium cruise line known for destination-rich itineraries and a strong culinary identity with refined small-ship ambiance.",
		highlights: ["Culinary excellence", "Premium small-ship feel", "Destination-focused journeys"],
	},
	{
		slug: "princess-cruises",
		name: "Princess Cruises",
		logoSrc: "/logos/princess-cruises_logo.svg",
		website: "https://www.princess.com",
		isLightLogo: false,
		tagline: "Relaxed premium voyages around the globe.",
		description: "Princess Cruises blends comfortable premium travel, strong destination coverage, and signature onboard experiences for global explorers.",
		highlights: ["Global itinerary coverage", "Relaxed premium style", "Strong destination programming"],
	},
	{
		slug: "regent-seven-seas",
		name: "Regent Seven Seas Cruises",
		logoSrc: "/logos/regent-seven-seas-cruises_logo.svg",
		website: "https://www.rssc.com",
		isLightLogo: false,
		tagline: "Ultra-luxury all-inclusive cruising.",
		description: "Regent Seven Seas delivers an ultra-luxury experience with spacious suites, premium inclusions, and globally curated itineraries.",
		highlights: ["Ultra-luxury positioning", "Comprehensive inclusions", "Suite-focused ships"],
	},
	{
		slug: "royal-caribbean-international",
		name: "Royal Caribbean International",
		logoSrc: "/logos/royal-caribbean_logo.svg",
		website: "https://www.royalcaribbean.com",
		isLightLogo: true,
		tagline: "Bold ships built for adventure.",
		description: "Royal Caribbean International is known for large, feature-rich ships and high-energy vacations with activities for all generations.",
		highlights: ["Adventure-forward ships", "Family and multigenerational appeal", "Innovative onboard activities"],
	},
	{
		slug: "virgin-voyages",
		name: "Virgin Voyages",
		logoSrc: "/logos/virgin-voyages_logo.svg",
		website: "https://www.virginvoyages.com",
		isLightLogo: false,
		tagline: "Adults-only lifestyle cruising.",
		description: "Virgin Voyages offers an adults-only cruise concept with contemporary design, vibrant dining, and entertainment-first experiences.",
		highlights: ["Adults-only concept", "Lifestyle-focused design", "Strong dining and nightlife"],
	},
	{
		slug: "viking-cruises",
		name: "Viking Cruises",
		logoSrc: "/logos/viking_logo.svg",
		website: "https://www.viking.com",
		isLightLogo: false,
		tagline: "River, ocean and expedition cruising redefined.",
		description: "Viking Cruises offers river and ocean cruises with a focus on cultural enrichment, elegant ships, and immersive itineraries.",
		highlights: ["Cultural enrichment", "Elegant ships", "Immersive itineraries"],
	},
	{
		slug: "scenic-cruises",
		name: "Scenic Cruises",
		logoSrc: "/logos/scenic_logo.svg",
		website: "https://www.scenic.com",
		isLightLogo: false,
		tagline: "Luxury river and ocean cruising.",
		description: "Scenic Cruises offers luxury river and ocean cruises with all-inclusive experiences and elegant ships.",
		highlights: ["Luxury all-inclusive cruising", "Elegant ships", "Scenic itineraries"],
	},
	{
		slug: "windstar-cruises",
		name: "Windstar Cruises",
		logoSrc: "/logos/windstar_logo.svg",
		website: "https://www.windstarcruises.com",
		isLightLogo: false,
		tagline: "Boutique sailing adventures.",
		description: "Windstar Cruises offers intimate sailing experiences with a focus on unique destinations, personalized service, and elegant ships.",
		highlights: ["Intimate sailing experience", "Unique destinations", "Personalized service"],
	},
	{
		slug: "seabourn",
		name: "Seabourn",
		logoSrc: "/logos/seabourn_logo.svg",
		website: "https://www.seabourn.com",
		isLightLogo: false,
		tagline: "Intimate ultra-luxury cruising.",
		description: "Seabourn offers an intimate ultra-luxury style with personalized service, curated experiences, and elegant all-suite ships.",
		highlights: ["Intimate ship scale", "Ultra-luxury service", "All-suite accommodations"],
	},
	{
		slug: "silversea",
		name: "Silversea",
		logoSrc: "/logos/silversea_logo.svg",
		website: "https://www.silversea.com",
		isLightLogo: true,
		tagline: "Luxury expeditions and classic luxury routes.",
		description: "Silversea combines classic ultra-luxury voyages and expedition experiences with butler service and globally diverse itineraries.",
		highlights: ["Ultra-luxury standards", "Expedition + classic portfolio", "Personalized butler service"],
	},
	{
		slug: "swan-hellenic",
		name: "Swan Hellenic",
		logoSrc: "/logos/swan-hellenic_logo.svg",
		website: "https://www.swanhellenic.com",
		isLightLogo: false,
		tagline: "Cultural expedition cruising.",
		description: "Swan Hellenic emphasizes cultural discovery and expedition travel with thoughtfully designed itineraries and expert enrichment.",
		highlights: ["Cultural exploration", "Expert enrichment", "Boutique expedition ships"],
	},
	{
		slug: "atlas-ocean-voyages",
		name: "Atlas Ocean Voyages",
		logoSrc: "/logos/atlas_logo.svg",
		website: "https://atlasoceanvoyages.com",
		isLightLogo: false,
		tagline: "Yachting expeditions and intimate luxury journeys.",
		description:
			"Atlas Ocean Voyages offers all-inclusive yacht-style cruises with a focus on curated shore experiences, wellness, and smaller-ship discovery itineraries.",
		highlights: ["Luxury expedition style", "Immersive shore programs", "All-inclusive onboard experience"],
	},
	{
		slug: "ponant",
		name: "Ponant",
		logoSrc: "/logos/ponant_logo.svg",
		website: "https://www.ponant.com",
		isLightLogo: false,
		tagline: "Luxury expedition cruising.",
		description: "Ponant offers luxury expedition cruises with elegant ships, immersive itineraries, and personalized service.",
		highlights: ["Luxury expedition experience", "Elegant ships", "Immersive itineraries"],
	},
	{
		slug: "quark-expeditions",
		name: "Quark Expeditions",
		logoSrc: "/logos/quark-expeditions_logo.svg",
		website: "https://www.quarkexpeditions.com",
		isLightLogo: false,
		tagline: "Polar expedition cruising.",
		description: "Quark Expeditions specializes in polar expeditions with expert-led itineraries and adventure-focused experiences.",
		highlights: ["Polar exploration", "Expert-led itineraries", "Adventure-focused experiences"],
	},
	{
		slug: "hurtigruten-expeditions",
		name: "Hurtigruten Expeditions",
		logoSrc: "/logos/hurtigruten-expeditions_logo.svg",
		website: "https://www.hurtigruten.com/expeditions",
		isLightLogo: false,
		tagline: "Polar expedition cruising.",
		description: "Hurtigruten Expeditions specializes in polar expeditions with expert-led itineraries and adventure-focused experiences.",
		highlights: ["Polar exploration", "Expert-led itineraries", "Adventure-focused experiences"],
	},
	{
		slug: "aurora-expeditions",
		name: "Aurora Expeditions",
		logoSrc: "/logos/aurora-expeditions_logo.svg",
		website: "https://www.auroraexpeditions.com",
		isLightLogo: false,
		tagline: "Polar expedition cruising.",
		description: "Aurora Expeditions specializes in polar expeditions with expert-led itineraries and adventure-focused experiences.",
		highlights: ["Polar exploration", "Expert-led itineraries", "Adventure-focused experiences"],
	},
];

export const SUPPLIERS_BY_SLUG = Object.fromEntries(SUPPLIERS.map((supplier) => [supplier.slug, supplier]));
